workflows:
  ios-app:
    name: iOS Build and Deploy
    max_build_duration: 60
    instance_type: mac_mini_m1  # 选择 macOS 服务器
    environment:
      xcode: latest  # 使用最新 Xcode 版本
      cocoapods: default  # 确保 CocoaPods 可用
      vars:
        XCODE_WORKSPACE: "YourApp.xcworkspace"  # 如果使用 Xcode workspace
        XCODE_SCHEME: "YourApp"
      groups:
        - app_store_credentials  # 存储 Apple 证书、Provisioning Profile

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Install dependencies
        script: |
          gem install bundler:2.4.22
          bundle install
          pod install

      - name: Build app
        script: |
          xcodebuild clean archive \
            -workspace $XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -archivePath build/YourApp.xcarchive \
            -allowProvisioningUpdates

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/YourApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ \
            -allowProvisioningUpdates

    artifacts:
      - build/*.ipa  # 导出 IPA 文件
      - build/*.xcarchive  # 归档文件
      - $HOME/Library/Logs/xcodebuild/*.log  # 构建日志

    publishing:
      app_store_connect:
        auth: integration
